# -*- coding: utf-8 -*-
"""horizonte2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JXloSC16MBFkb_oOhR5coTOVb2CHXZwe
"""

import streamlit as st
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
import numpy as np
import io
import base64
from datetime import datetime

# --- CONFIGURACIÓN DE LA PÁGINA Y CONSTANTES ---
st.set_page_config(
    page_title="Plataforma Horizonte Empresarial 360",
    layout="wide",
    initial_sidebar_state="expanded"
)

# Constantes de Autenticación
DEMO_USER = "usuario_demo"
DEMO_PASSWORD = "demo360"
HORIZONTE_PROYECCION_DEFAULT = 6

# --- ESTRUCTURA DE MÓDULOS (Orden Exacto Solicitado) ---
MODULOS = {
    "Gobernanza": "1. Gobernanza y Dueños (Visión Ejecutiva)",
    "Financiero": "2. 💰 Módulo Financiero Inteligente",
    "Ambiental": "3. 🌳 Riesgos, Sostenibilidad y Cumplimiento (Ambiental)",
    "HSEQ": "4. ⚠️ Riesgos y Cumplimiento (HSEQ + Legal + Laboral)",
    "RRHH": "5. 🧑‍💼 Sostenibilidad Social (RRHH)",
    "Comercial": "6. 🛒 Módulo Comercial",
    "Productividad": "7. 🛠️ Módulo de Productividad y Procesos"
}

# --- FUNCIONES DE SERVICIO ---

def check_password():
    """Funcionalidad 3: Autenticación simulada."""
    if "password_correct" not in st.session_state:
        st.session_state["password_correct"] = False

    if st.session_state["password_correct"]:
        return True

    st.title("PLATAFORMA HORIZONTE EMPRESARIAL 360")
    st.markdown("Estudio de Caso: Acuamar S.A.")
    st.info("Ofrece una visión integral del negocio, revelando patrones, tendencias y oportunidades ocultas a través de un análisis profundo y una plataforma diseñada para la toma de decisiones estratégicas.")
    st.markdown("---")
    st.subheader("🔐 Iniciar Sesión")
    st.caption("Credenciales de Demo: `usuario_demo` / `demo360`")

    with st.form("login_form"):
        username = st.text_input("Usuario")
        password = st.text_input("Contraseña", type="password")
        submitted = st.form_submit_button("Ingresar")

        if submitted:
            if username == DEMO_USER and password == DEMO_PASSWORD:
                st.session_state["password_correct"] = True
                st.experimental_rerun()
            else:
                st.error("❌ Usuario o Contraseña incorrectos.")

    return False

def get_placeholder_data(horizon):
    """Genera datos de placeholder simulados."""
    dates = pd.date_range(end=datetime.now(), periods=12, freq='M')
    proj_dates = pd.date_range(start=dates[-1], periods=horizon + 1, freq='M')[1:]

    data = {
        'FECHA': dates,
        'Ventas_Gravadas': np.random.randint(50_000_000, 100_000_000, 12),
        'Pagos_Proveedores': np.random.randint(20_000_000, 50_000_000, 12),
        'Consumo_Energia': np.random.rand(12) * 5000,
        'Coste_Energia': np.random.rand(12) * 10_000_000,
        'Tasa_Defectos': np.random.rand(12) * 5,
        'Costo_Oculto': np.random.randint(1_000_000, 5_000_000, 12),
        'Clientes_Activos': np.random.randint(30, 80, 12),
        'Valor_Promedio_Venta': np.random.randint(500_000, 2_000_000, 12),
        'Tasa_Retencion_RRHH': np.random.rand(12) * 90 + 5,
        'Costo_Sanciones': np.random.rand(12) * 5_000_000,
    }
    df = pd.DataFrame(data)
    df['FECHA'] = pd.to_datetime(df['FECHA'])
    return df, proj_dates


def process_loaded_data(uploaded_files_map):
    """
    Función para procesar archivos, separar DataFrames y realizar limpieza inicial.
    Simula la separación de datos por hojas o archivos, según el flujo del notebook.
    """

    # Intenta consolidar o separar DataFrames
    all_dfs = get_placeholder_data(1).drop(columns=['FECHA'])[0].T.to_dict('list') # Placeholder para estructura

    # Asume que el usuario sube un archivo que contiene las hojas/datos necesarios
    for file_name, uploaded_file in uploaded_files_map.items():
        try:
            # Si es Excel, intenta leer varias hojas. Si no, solo el archivo.
            if uploaded_file.name.endswith(('.xlsx', '.xls')):
                xls = pd.ExcelFile(uploaded_file)
                # Simula la lógica de separar por hojas

                # Hoja 1: Financiero/Comercial
                if 'Financiero' in xls.sheet_names or 'Ventas' in xls.sheet_names:
                    temp_df = pd.read_excel(xls, sheet_name=xls.sheet_names[0])
                    # Simulación de mapeo (En producción, esto sería un mapeo de columnas real)
                    st.session_state.df_fin = temp_df.copy() # df_fin
                    st.session_state.df_com = temp_df.copy() # df_com

                # Hoja 2: Sostenibilidad/Riesgos/RRHH/Productividad
                if 'Sostenibilidad' in xls.sheet_names or 'HSEQ' in xls.sheet_names:
                    temp_df = pd.read_excel(xls, sheet_name=xls.sheet_names[1])
                    st.session_state.df_sost = temp_df.copy() # df_sost (Ambiental)
                    st.session_state.df_riesgos = temp_df.copy() # df_riesgos (HSEQ)
                    st.session_state.df_rrhh = temp_df.copy() # df_rrhh
                    st.session_state.df_prod = temp_df.copy() # df_prod

            elif uploaded_file.name.endswith('.csv'):
                # Si es CSV, asumimos que es un archivo consolidado para simplificar
                temp_df = pd.read_csv(uploaded_file)
                st.session_state.df_fin = temp_df.copy()
                st.session_state.df_com = temp_df.copy()
                st.session_state.df_sost = temp_df.copy()
                st.session_state.df_riesgos = temp_df.copy()
                st.session_state.df_rrhh = temp_df.copy()
                st.session_state.df_prod = temp_df.copy()

            st.success(f"✅ Archivo '{uploaded_file.name}' cargado y DataFrames separados (Simulado).")
            break # Procesa solo el primer archivo para este ejemplo.

        except Exception as e:
             st.error(f"❌ Error al procesar el archivo '{uploaded_file.name}': {e}. Se usarán datos simulados.")

    st.experimental_rerun() # Recarga para que los datos aparezcan en los módulos


def load_data_from_upload():
    """Funcionalidad 1: Carga de Archivos (Permite múltiples archivos)."""
    st.sidebar.header("📁 Carga de Archivos")
    uploaded_files = st.sidebar.file_uploader(
        "Sube los archivos (Excel, CSV o Parquet)",
        type=["xlsx", "xls", "csv", "parquet"],
        accept_multiple_files=True
    )

    if uploaded_files:
        st.session_state['uploaded_files_map'] = {file.name: file for file in uploaded_files}
        st.sidebar.success(f"✅ {len(uploaded_files)} archivos listos para procesar.")

        if st.sidebar.button("Procesar y Separar DataFrames"):
            process_loaded_data(st.session_state['uploaded_files_map'])

def connect_to_sql_db():
    """Funcionalidad 2: Conexión SQL (Placeholder Visual)."""
    st.sidebar.markdown("---")
    st.sidebar.header("📡 Conexión a Base de Datos SQL")
    st.sidebar.markdown("🟢 **Estado: Conectado (Simulado)**")

def display_kpi_card(title, value, delta, format_string=""):
    """Función helper para mostrar tarjetas KPI con formato."""
    if format_string:
        display_value = format_string.format(value)
    else:
        display_value = f"{value:,.0f}" if isinstance(value, (int, float)) else str(value)

    st.metric(label=title, value=display_value, delta=f"{delta:,.2f}% vs Base" if delta is not None else None)

def create_pdf_report(df_results, module_name):
    """Funcionalidad 4: Simula la creación de un reporte PDF usando CSV/BytesIO."""
    csv_buffer = io.StringIO()
    df_results.to_csv(csv_buffer, index=False)
    csv_bytes = csv_buffer.getvalue().encode()
    return base64.b64encode(csv_bytes).decode()


# --- MÓDULOS COMPLETOS (EDA, Predicciones/Simulaciones) ---

def display_modulo_gobernanza(horizon):
    """Módulo 1: Gobernanza y Dueños (Visión Ejecutiva)."""

    st.subheader("Resumen y Decisión Ejecutiva")
    st.info("Este módulo consolida los KPIs críticos de todos los módulos. Aquí se toman decisiones estratégicas basándose en proyecciones.")

    col1, col2, col3, col4 = st.columns(4)
    with col1:
        display_kpi_card("Riesgo Financiero (Proyectado)", 7.5, -0.5, format_string="{:.2f}%")
    with col2:
        display_kpi_card("Tasa de Retención (RRHH)", 88.3, 1.2, format_string="{:.1f}%")
    with col3:
        display_kpi_card("Ahorro Potencial (Productividad)", 15_000_000, None, format_string="COP {:,}")
    with col4:
        display_kpi_card("Riesgo Ambiental (Puntaje)", 35, 3, format_string="{:.0f} pts")

    st.markdown("---")
    st.subheader("Gráfico: Scorecard Consolidado de Riesgo vs Oportunidad")

    df_scorecard = pd.DataFrame({
        'Módulo': ['Financiero', 'Comercial', 'Sostenibilidad', 'Productividad'],
        'Riesgo (%)': [7.5, 4.0, 6.0, 3.5],
        'Oportunidad (%)': [12.0, 18.0, 8.0, 25.0]
    })

    fig = px.bar(df_scorecard, x='Módulo', y=['Riesgo (%)', 'Oportunidad (%)'],
                 barmode='group', title='Matriz Consolidada de Riesgo y Oportunidad')
    st.plotly_chart(fig, use_container_width=True)

    st.success(f"Decisión para el horizonte de **{horizon} meses**: Inversión prioritaria en Productividad y Comercial.")


def display_modulo_financiero(horizon):
    """Módulo 2: Financiero Inteligente (Flujo de Caja y Riesgo Financiero)."""

    df_fin, proj_dates = get_placeholder_data(horizon) # Usa placeholder si no se carga

    st.subheader("1. Análisis Exploratorio (EDA)")

    # KPIs
    margen_bruto_base = ((df_fin['Ventas_Gravadas'].sum() - df_fin['Pagos_Proveedores'].sum()) / df_fin['Ventas_Gravadas'].sum()) * 100
    dcp_base = np.random.uniform(30, 60)

    col1, col2 = st.columns(2)
    with col1:
        display_kpi_card("Margen Bruto Promedio", margen_bruto_base, 0.0, format_string="{:.2f}%")
    with col2:
        display_kpi_card("Días de Cartera Promedio (DCP)", dcp_base, -1.5, format_string="{:.1f} días")

    # Gráfico (EDA)
    st.subheader("Evolución de Flujo de Caja Histórico")
    df_fin['Flujo_Neto'] = df_fin['Ventas_Gravadas'] - df_fin['Pagos_Proveedores']
    fig_eda = px.line(df_fin, x='FECHA', y='Flujo_Neto', title='Flujo Neto Mensual Histórico')
    st.plotly_chart(fig_eda, use_container_width=True)

    st.markdown("---")
    st.subheader("2. Simulación de Flujo y Riesgo (Funcionalidades 5 y 6)")

    with st.expander("⚙️ Ingreso Datos Simulación (Monte Carlo)"):
        col1, col2 = st.columns(2)
        ajuste_cobros = col1.slider("Ajuste Cobros (%): Rotación de Cartera", min_value=-10.0, max_value=10.0, value=0.0, step=0.5)
        ajuste_pagos = col2.number_input("Tasa Crecimiento Pagos Anual Esperada (%)", min_value=0.0, max_value=20.0, value=5.0, step=0.1, format="%.1f")

        if st.button("▶️ Ejecutar Simulación", key="fin_sim"):
            sim_net_flow = np.random.randint(15_000_000, 50_000_000, horizon) + ajuste_cobros * 500_000 - ajuste_pagos * 100_000
            sim_risk = np.random.rand(horizon) * 10 + 5 - ajuste_cobros * 0.1

            df_sim_result = pd.DataFrame({
                'Fecha': proj_dates,
                'Flujo_Neto_Proyectado': sim_net_flow,
                'Riesgo_Incumplimiento': sim_risk
            })
            st.session_state['df_simulacion_financiera'] = df_sim_result
            st.success(f"Simulación ejecutada para **{horizon} meses**.")

    df_sim = st.session_state.get('df_simulacion_financiera')
    if df_sim is not None:
        st.subheader("Resultados de Proyección de Flujo de Caja")
        fig_flujo = px.line(df_sim, x='Fecha', y=['Flujo_Neto_Proyectado', 'Riesgo_Incumplimiento'],
                           title=f'Proyección de Flujo Neto y Riesgo a {horizon} meses',
                           labels={'value': 'Valor'}, markers=True)
        st.plotly_chart(fig_flujo, use_container_width=True)

        # Funcionalidad 4: Botón de Descarga
        b64_content = create_pdf_report(df_sim, "Financiero")
        st.download_button(
            label="⬇️ Descargar Reporte Flujo de Caja (PDF Simulado)",
            data=base64.b64decode(b64_content),
            file_name=f"Reporte_Financiero_{horizon}_meses.pdf",
            mime="application/octet-stream"
        )


def display_modulo_ambiental(horizon):
    """Módulo 3: Sostenibilidad (Huellas de Carbono/Hídrica y Riesgo Regulatorio)."""

    df_sost, _ = get_placeholder_data(horizon) # Usa placeholder si no se carga

    st.subheader("1. Análisis Exploratorio (EDA)")

    # KPIs
    consumo_energia_avg = df_sost['Consumo_Energia'].mean().round(0)
    coste_energia_total = df_sost['Coste_Energia'].sum()

    col1, col2 = st.columns(2)
    with col1:
        display_kpi_card("Consumo Promedio de Energía (kWh)", consumo_energia_avg, -2, format_string="{:,.0f}")
    with col2:
        display_kpi_card("Costo Total Histórico de Energía", coste_energia_total, 10, format_string="COP {:,}")

    # Gráfico (EDA)
    st.subheader("Consumo vs. Costo Histórico de Energía")
    fig_consumo = go.Figure()
    fig_consumo.add_trace(go.Bar(x=df_sost['FECHA'], y=df_sost['Consumo_Energia'], name='Consumo (kWh)', yaxis='y1', opacity=0.7))
    fig_consumo.add_trace(go.Scatter(x=df_sost['FECHA'], y=df_sost['Coste_Energia'], name='Costo Total (COP)', yaxis='y2', mode='lines+markers', line=dict(color='red')))

    fig_consumo.update_layout(title='Análisis de Costo-Eficiencia Energética', yaxis2=dict(title="Costo Total (COP)", side="right", overlaying="y"))
    st.plotly_chart(fig_consumo, use_container_width=True)

    st.markdown("---")
    st.subheader("2. Simulación de Huella de Carbono y Riesgo Regulatorio")

    # Simulación de Riesgo Ambiental
    with st.expander("⚙️ Medidor de Riesgo Regulatorio y Simulación de Inversión"):
        inversion_mitigacion = st.slider("Inversión en Mitigación de Huella (COP Millones)", min_value=0, max_value=100, value=10, step=5)

        if st.button("▶️ Proyectar Reducción de Riesgo", key="amb_sim"):
            riesgo_proyectado = 35 - (inversion_mitigacion / 10)
            riesgo_proyectado = max(riesgo_proyectado, 10) # Límite inferior
            st.metric("Riesgo Regulatorio Proyectado", f"{riesgo_proyectado:.1f} pts", f"-{(35 - riesgo_proyectado):.1f} pts de reducción")
            st.success(f"Proyección a {horizon} meses: La inversión reduce el riesgo.")


def display_modulo_hseq(horizon):
    """Módulo 4: Riesgos y Cumplimiento (HSEQ + Legal + Laboral)."""

    df_riesgos, proj_dates = get_placeholder_data(horizon) # Usa placeholder si no se carga

    st.subheader("1. Análisis Exploratorio (EDA)")

    # KPIs
    costo_no_conformidad = df_riesgos['Costo_Sanciones'].sum() * 1.5
    incidencia_legal = np.random.uniform(0.5, 2.5)

    col1, col2 = st.columns(2)
    with col1:
        display_kpi_card("Costo Anual No-Conformidad", costo_no_conformidad, 0, format_string="COP {:,}")
    with col2:
        display_kpi_card("Índice de Incidencia Legal", incidencia_legal, None, format_string="{:.2f}")

    # Gráfico (EDA)
    st.subheader("Distribución de Costos de Sanciones Históricas")
    fig_sanciones = px.pie(df_riesgos.head(5), values='Costo_Sanciones', names='FECHA',
                           title='Distribución Histórica de Costos por Sanciones (Ejemplo)')
    st.plotly_chart(fig_sanciones, use_container_width=True)

    st.markdown("---")
    st.subheader("2. Predicción de Accidentalidad Laboral")

    # Predicción (Simulación)
    with st.expander("⚙️ Factores de Riesgo para Predicción de Accidentalidad"):
        factor_capacitacion = st.slider("Nivel de Capacitación (1=Bajo, 5=Alto)", 1, 5, 3)

        if st.button("▶️ Predecir Tasa de Accidentalidad", key="hseq_pred"):
            tasa_accidentalidad = 5.0 - (factor_capacitacion * 0.5)
            st.metric("Tasa de Accidentalidad Proyectada", f"{tasa_accidentalidad:.2f}%", f"Riesgo a {horizon} meses")
            st.error("🚨 **Riesgo de Accidentalidad:** Requiere plan de mejora si el valor supera el 3.0%.")


def display_modulo_rrhh(horizon):
    """Módulo 5: Sostenibilidad Social (RRHH) - Costo del Capital Humano y Riesgo de Retención."""

    df_rrhh, proj_dates = get_placeholder_data(horizon) # Usa placeholder si no se carga

    st.subheader("1. Análisis Exploratorio (EDA)")

    # KPIs
    tasa_retencion = df_rrhh['Tasa_Retencion_RRHH'].mean()
    costo_cap_humano = np.random.randint(100_000_000, 200_000_000)

    col1, col2 = st.columns(2)
    with col1:
        display_kpi_card("Tasa de Retención Actual", tasa_retencion, -1.5, format_string="{:.1f}%")
    with col2:
        display_kpi_card("Costo Anual del Capital Humano", costo_cap_humano, None, format_string="COP {:,}")

    # Gráfico (EDA)
    st.subheader("Evolución de la Tasa de Retención Histórica")
    fig_retencion = px.bar(df_rrhh, x='FECHA', y='Tasa_Retencion_RRHH',
                           title='Tasa de Retención por Mes',
                           labels={'Tasa_Retencion_RRHH': 'Tasa (%)', 'FECHA': 'Fecha'})
    st.plotly_chart(fig_retencion, use_container_width=True)

    st.markdown("---")
    st.subheader("2. Predicción de Riesgo de Rotación")

    # Predicción (Simulación)
    with st.expander("⚙️ Factores de Influencia en la Rotación"):
        factor_salario = st.number_input("Ajuste Salarial Promedio (Incremento %)", min_value=0.0, max_value=10.0, value=4.0, step=0.5)

        if st.button("▶️ Proyectar Riesgo de Rotación", key="rrhh_pred"):
            riesgo_rotacion = 15.0 - (factor_salario * 1.5)
            riesgo_rotacion = max(riesgo_rotacion, 5.0) # Límite inferior
            st.metric("Riesgo de Rotación Proyectado", f"{riesgo_rotacion:.1f}%", f"A {horizon} meses")
            st.info(f"El modelo predice un riesgo del {riesgo_rotacion:.1f}% para el horizonte de {horizon} meses.")


def display_modulo_comercial(horizon):
    """Módulo 6: Comercial (Ingresos y Precios Óptimos)."""

    df_com, proj_dates = get_placeholder_data(horizon) # Usa placeholder si no se carga

    st.subheader("1. Análisis Exploratorio (EDA)")

    # KPIs
    clientes_activos = df_com['Clientes_Activos'].mean().round(0)
    aov = df_com['Valor_Promedio_Venta'].mean()

    col1, col2, col3 = st.columns(3)
    with col1:
        display_kpi_card("Clientes Activos Promedio", clientes_activos, 5)
    with col2:
        display_kpi_card("Valor Promedio de Venta (AOV)", aov, 1.5, format_string="COP {:,}")
    with col3:
        display_kpi_card("Ingresos Totales (Base)", df_com['Ventas_Gravadas'].sum(), 10, format_string="COP {:,}")

    # Gráfico (EDA)
    st.subheader("Evolución Histórica de Ventas vs Clientes")
    fig_ventas = px.line(df_com, x='FECHA', y=['Ventas_Gravadas', 'Clientes_Activos'],
                        title='Ventas Gravadas Mensuales vs. Clientes Activos',
                        labels={'value': 'Métrica'})
    st.plotly_chart(fig_ventas, use_container_width=True)

    st.markdown("---")
    st.subheader("2. Determinación de Precios Óptimos (Elasticidad)")

    # Simulación
    with st.expander("⚙️ Simulación de Elasticidad de Precios"):
        ajuste_precio = st.slider("Ajuste de Precio (Simulación %)", min_value=-10.0, max_value=10.0, value=0.0, step=1.0)

        if st.button("▶️ Proyectar Ingresos Netos", key="com_sim"):
            # Lógica simulada de elasticidad: un aumento de precio reduce las ventas, pero aumenta el AOV
            elasticidad = -1.5 # Simulación: demanda elástica
            cambio_ventas_unitario = ajuste_precio * elasticidad

            ingreso_proyectado = df_com['Ventas_Gravadas'].mean() * 12 * (1 + cambio_ventas_unitario/100)

            st.metric("Ingreso Anual Proyectado", f"COP {ingreso_proyectado:,.0f}", f"{cambio_ventas_unitario:.1f}% de cambio en unidades")
            st.warning(f"La demanda es elástica (Elasticidad {elasticidad}). Un aumento del precio del {ajuste_precio}% resultará en una caída en el volumen.")


def display_modulo_productividad(horizon):
    """Módulo 7: Productividad y Procesos (Eficiencia Operativa y Costos Ocultos)."""

    df_prod, proj_dates = get_placeholder_data(horizon) # Usa placeholder si no se carga

    st.subheader("1. Análisis Exploratorio (EDA)")

    # KPIs
    tasa_defectos_base = df_prod['Tasa_Defectos'].mean()
    costo_oculto_base = df_prod['Costo_Oculto'].sum()

    col1, col2 = st.columns(2)
    with col1:
        display_kpi_card("Tasa de Defectos (Base)", tasa_defectos_base, None, format_string="{:.2f}%")
    with col2:
        display_kpi_card("Costo Oculto (Base)", costo_oculto_base, None, format_string="COP {:,}")

    # Gráfico (EDA)
    st.subheader("Tendencia Histórica de la Tasa de Defectos")
    fig_defectos = px.line(df_prod, x='FECHA', y='Tasa_Defectos',
                           title='Tasa de Defectos por Mes',
                           labels={'Tasa_Defectos': 'Tasa (%)', 'FECHA': 'Fecha'},
                           markers=True)
    st.plotly_chart(fig_defectos, use_container_width=True)

    st.markdown("---")
    st.subheader("2. Simulación de Ahorro por Mejora de Procesos (Lean)")

    # Simulación
    with st.expander("⚙️ Simulación de Reducción de Costos Ocultos"):
        reduccion_defectos_pct = st.slider("Reducción Meta en Tasa de Defectos (%)", min_value=0.0, max_value=50.0, value=10.0, step=1.0)

        if st.button("▶️ Proyectar Ahorro", key="prod_sim"):
            nueva_tasa_defectos = tasa_defectos_base * (1 - reduccion_defectos_pct / 100)
            reduccion_costo_proyectada = costo_oculto_base * (reduccion_defectos_pct / 100)

            col3, col4 = st.columns(2)
            with col3:
                st.metric("Tasa Proyectada (Mejora)", f"{nueva_tasa_defectos:.2f}%", f"{(tasa_defectos_base - nueva_tasa_defectos):.2f}% menos")
            with col4:
                st.metric("Ahorro Proyectado", f"COP {reduccion_costo_proyectada:,.0f}", "Ahorro Estimado Anual")
            st.success(f"La mejora en la tasa de defectos genera un ahorro de COP {reduccion_costo_proyectada:,.0f} a {horizon} meses.")


# --- FLUJO PRINCIPAL DE LA APLICACIÓN ---
if __name__ == "__main__":
    if check_password():
        # --- Sidebar ---
        connect_to_sql_db()
        load_data_from_upload()

        # --- Cabecera Post-Login ---
        st.title("ACUAMAR S.A.")
        st.caption("Empresa manufacturera y distribuidora de productos químicos de limpieza e higiene industrial")

        # Funcionalidad 5: BARRA DE PREDICCIÓN (Slider global)
        horizonte_proyeccion = st.slider(
            "Horizonte (Meses): Periodo para todas las proyecciones y simulaciones.",
            min_value=1,
            max_value=36,
            value=HORIZONTE_PROYECCION_DEFAULT,
            step=1,
            key='global_horizonte'
        )
        st.markdown("---")

        # --- Navegación por Módulos (Tabs) ---

        # Se crean las pestañas en el orden exacto de MODULOS
        tabs_list = st.tabs(list(MODULOS.values()))

        # Mapeo de funciones a pestañas
        module_functions = [
            display_modulo_gobernanza,
            display_modulo_financiero,
            display_modulo_ambiental,
            display_modulo_hseq,
            display_modulo_rrhh,
            display_modulo_comercial,
            display_modulo_productividad
        ]

        # Renderizado de pestañas
        for i, tab in enumerate(tabs_list):
            with tab:
                # Todas las funciones se llaman con el Horizonte de Proyección
                module_functions[i](horizonte_proyeccion)