# -*- coding: utf-8 -*-
"""horizonte

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JXloSC16MBFkb_oOhR5coTOVb2CHXZwe
"""

import streamlit as st
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
import numpy as np
import io
import base64
from datetime import datetime

# --- CONFIGURACIÓN DE LA PÁGINA Y CONSTANTES ---
st.set_page_config(
    page_title="Plataforma Horizonte Empresarial 360",
    layout="wide",
    initial_sidebar_state="expanded"
)

# Constantes de Autenticación
DEMO_USER = "usuario_demo"
DEMO_PASSWORD = "demo360"
HORIZONTE_PROYECCION_DEFAULT = 6

# --- ESTRUCTURA DE MÓDULOS (Según DOCX) ---
MODULOS = {
    "Gobernanza": "1. Gobernanza y Dueños (Visión Ejecutiva)",
    "Financiero": "2. 💰 Módulo Financiero Inteligente",
    "Ambiental": "3. 🌳 Riesgos, Sostenibilidad y Cumplimiento (Ambiental)",
    "HSEQ": "4. ⚠️ Riesgos y Cumplimiento (HSEQ + Legal + Laboral)",
    "RRHH": "5. 🧑‍💼 Sostenibilidad Social (RRHH)",
    "Comercial": "6. 🛒 Módulo Comercial",
    "Productividad": "7. 🛠️ Módulo de Productividad y Procesos"
}

# --- FUNCIONES DE SERVICIO (Funcionalidades 1, 2, 3, 4) ---

def check_password():
    """Funcionalidad 3: Autenticación simulada."""
    if "password_correct" not in st.session_state:
        st.session_state["password_correct"] = False

    if st.session_state["password_correct"]:
        return True

    # Interfaz Pre-Login con Título e Introducción
    st.title("PLATAFORMA HORIZONTE EMPRESARIAL 360")
    st.markdown("Estudio de Caso: Acuamar S.A.")
    st.info("Ofrece una visión integral del negocio, revelando patrones, tendencias y oportunidades ocultas a través de un análisis profundo y una plataforma diseñada para la toma de decisiones estratégicas.")
    st.markdown("---")
    st.subheader("🔐 Iniciar Sesión")
    st.caption("Credenciales de Demo: `usuario_demo` / `demo360`")

    with st.form("login_form"):
        username = st.text_input("Usuario")
        password = st.text_input("Contraseña", type="password")
        submitted = st.form_submit_button("Ingresar")

        if submitted:
            if username == DEMO_USER and password == DEMO_PASSWORD:
                st.session_state["password_correct"] = True
                st.experimental_rerun()
            else:
                st.error("❌ Usuario o Contraseña incorrectos.")

    return False

def load_data_from_upload():
    """Funcionalidad 1: Carga de Archivos Excel/csv/parquet."""
    st.sidebar.header("📁 Carga de Datos")
    uploaded_file = st.sidebar.file_uploader(
        "Sube tu archivo (Excel, CSV o Parquet)",
        type=["xlsx", "xls", "csv", "parquet"],
        accept_multiple_files=False
    )

    if uploaded_file is not None:
        try:
            file_extension = uploaded_file.name.split('.')[-1].lower()
            df_data = None

            if file_extension in ["xlsx", "xls"]:
                # Lee la primera hoja del Excel
                xls = pd.ExcelFile(uploaded_file)
                df_data = pd.read_excel(xls, sheet_name=xls.sheet_names[0])
            elif file_extension == "csv":
                df_data = pd.read_csv(uploaded_file)
            elif file_extension == "parquet":
                df_data = pd.read_parquet(uploaded_file)

            if df_data is not None:
                 st.session_state['df_data'] = df_data
                 st.sidebar.success("✅ Datos cargados correctamente.")
                 st.sidebar.dataframe(df_data.head(2), use_container_width=True)

        except Exception as e:
            st.sidebar.error(f"❌ Error al leer el archivo: {e}")

def connect_to_sql_db():
    """Funcionalidad 2: Conexión SQL (Placeholder Visual)."""
    st.sidebar.markdown("---")
    st.sidebar.header("📡 Conexión a Base de Datos SQL")
    st.sidebar.markdown("🟢 **Estado: Conectado (Simulado)**")

def create_pdf_report(df_results, module_name):
    """Funcionalidad 4: Simula la creación de un reporte PDF usando CSV/BytesIO."""

    csv_buffer = io.StringIO()
    df_results.to_csv(csv_buffer, index=False)
    csv_bytes = csv_buffer.getvalue().encode()

    return base64.b64encode(csv_bytes).decode()

# --- FUNCIONES DE VISUALIZACIÓN DE MÓDULOS (KPIs y Gráficos) ---

def display_kpi_card(title, value, delta, help_text=None, format_string=""):
    """Función helper para mostrar tarjetas KPI con formato."""
    if format_string:
        display_value = format_string.format(value)
    else:
        display_value = f"{value:,.0f}" if isinstance(value, (int, float)) else str(value)

    st.metric(label=title, value=display_value, delta=f"{delta:,.2f}% vs Base" if delta is not None else None, help=help_text)

def get_placeholder_data(horizon):
    """Genera datos de placeholder simulados para los módulos."""
    dates = pd.date_range(end=datetime.now(), periods=12, freq='M')
    proj_dates = pd.date_range(start=dates[-1], periods=horizon + 1, freq='M')[1:]

    data = {
        'FECHA': dates,
        'Ventas_Gravadas': np.random.randint(50_000_000, 100_000_000, 12),
        'Pagos_Proveedores': np.random.randint(20_000_000, 50_000_000, 12),
        'Consumo_Energia': np.random.rand(12) * 5000,
        'Coste_Energia': np.random.rand(12) * 10_000_000,
        'Tasa_Defectos': np.random.rand(12) * 5,
        'Costo_Oculto': np.random.randint(1_000_000, 5_000_000, 12),
        'Clientes_Activos': np.random.randint(30, 80, 12),
        'Valor_Promedio_Venta': np.random.randint(500_000, 2_000_000, 12),
        'Tasa_Retencion_RRHH': np.random.rand(12) * 90 + 5
    }
    df = pd.DataFrame(data)
    df['FECHA'] = pd.to_datetime(df['FECHA'])
    return df, proj_dates


# --- MÓDULO 1: GOBERNANZA ---
def display_modulo_gobernanza(df_data, horizon):
    """Módulo 1: Gobernanza y Dueños (Visión Ejecutiva)."""
    st.subheader("Resumen y Decisión Ejecutiva")
    st.info("Este módulo consolida los KPIs críticos de todos los módulos para una toma de decisiones estratégica.")

    # Placeholder de KPIs consolidados
    col1, col2, col3 = st.columns(3)
    with col1:
        display_kpi_card("Riesgo Financiero Consolidado", 7.5, -0.5, format_string="{:.2f}%")
    with col2:
        display_kpi_card("Tasa de Retención (RRHH)", 88.3, 1.2, format_string="{:.1f}%")
    with col3:
        display_kpi_card("Ahorro Potencial (Productividad)", 15_000_000, None, format_string="COP {:,}")


# --- MÓDULO 2: FINANCIERO INTELIGENTE ---
def display_modulo_financiero(df_data, horizon):
    """Módulo 2: Financiero Inteligente (Flujo de Caja y Riesgo Financiero)."""

    df, proj_dates = get_placeholder_data(horizon)

    # Cálculos de KPIs Simulados
    margen_bruto_base = ((df['Ventas_Gravadas'].sum() - df['Pagos_Proveedores'].sum()) / df['Ventas_Gravadas'].sum()) * 100
    dcp_base = np.random.uniform(30, 60)

    # FUNCIONALIDADES 5 y 6: Simulación y Horizonte
    st.subheader("Simulación de Flujo de Caja y Riesgo (Monte Carlo)")

    with st.expander("⚙️ Ingreso Datos Simulación: Ajuste de Variables Clave (Funcionalidad 6)"):
        col1, col2 = st.columns(2)
        ajuste_cobros = col1.slider("Ajuste Cobros (%): Rotación de Cartera", min_value=-10.0, max_value=10.0, value=0.0, step=0.5)
        ajuste_pagos = col2.number_input("Tasa Crecimiento Pagos Anual Esperada (%)", min_value=0.0, max_value=20.0, value=5.0, step=0.1, format="%.1f")

        if st.button("▶️ Ejecutar Simulación"):
            # Lógica de Simulación
            sim_net_flow = np.random.randint(15_000_000, 50_000_000, horizon) + ajuste_cobros * 500_000 - ajuste_pagos * 100_000
            sim_risk = np.random.rand(horizon) * 10 + 5 - ajuste_cobros * 0.1

            df_sim_result = pd.DataFrame({
                'Fecha': proj_dates,
                'Flujo_Neto_Proyectado': sim_net_flow,
                'Riesgo_Incumplimiento': sim_risk
            })
            st.session_state['df_simulacion_financiera'] = df_sim_result
            st.success(f"Simulación ejecutada para **{horizon} meses**.")

    col1, col2 = st.columns(2)
    with col1:
        display_kpi_card("Margen Bruto Aprox.", margen_bruto_base, 0.0, format_string="{:.2f}%")
    with col2:
        display_kpi_card("Días de Cartera Promedio (DCP)", dcp_base, ajuste_cobros * -0.5, format_string="{:.1f} días")

    df_sim = st.session_state.get('df_simulacion_financiera')
    if df_sim is not None:
        st.subheader("Gráfico: Flujo de Caja Proyectado")
        fig_flujo = px.line(df_sim, x='Fecha', y='Flujo_Neto_Proyectado',
                           title=f'Proyección de Flujo Neto a {horizon} meses',
                           labels={'Flujo_Neto_Proyectado': 'Flujo Neto (COP)', 'Fecha': 'Mes'},
                           markers=True)
        st.plotly_chart(fig_flujo, use_container_width=True)

        # Funcionalidad 4: Botón de Descarga
        b64_content = create_pdf_report(df_sim, "Financiero")
        st.download_button(
            label="⬇️ Descargar Reporte Flujo de Caja (PDF Simulado)",
            data=base64.b64decode(b64_content),
            file_name=f"Reporte_Financiero_{horizon}_meses.pdf",
            mime="application/octet-stream"
        )
    else:
        st.warning("Ejecuta la simulación para ver la proyección y el botón de descarga.")


# --- MÓDULO 3: AMBIENTAL ---
def display_modulo_ambiental(df_data, horizon):
    """Módulo 3: Sostenibilidad (Huella de Carbono/Hídrica y Riesgo Regulatorio)."""

    df, _ = get_placeholder_data(horizon)
    consumo_energia_avg = df['Consumo_Energia'].mean().round(0)
    coste_energia_total = df['Coste_Energia'].sum()

    col1, col2 = st.columns(2)
    with col1:
        display_kpi_card("Consumo Promedio de Energía (kWh)", consumo_energia_avg, -2, format_string="{:,.0f}")
    with col2:
        display_kpi_card("Costo Total Histórico de Energía", coste_energia_total, 10, format_string="COP {:,}")

    st.markdown("---")
    st.subheader("Gráfico: Consumo vs. Costo Histórico de Energía")

    fig_consumo = go.Figure()

    # Eje Y1: Consumo
    fig_consumo.add_trace(go.Bar(x=df['FECHA'], y=df['Consumo_Energia'], name='Consumo (kWh)', yaxis='y1', opacity=0.7))
    # Eje Y2: Costo Total
    fig_consumo.add_trace(go.Scatter(x=df['FECHA'], y=df['Coste_Energia'], name='Costo Total (COP)', yaxis='y2', mode='lines+markers', line=dict(color='red')))

    fig_consumo.update_layout(
        title='Análisis de Costo-Eficiencia Energética',
        xaxis=dict(title="Fecha"),
        yaxis=dict(title="Consumo (kWh)", side="left", showgrid=False),
        yaxis2=dict(title="Costo Total (COP)", side="right", overlaying="y", showgrid=True),
        legend=dict(x=0.1, y=1.1, orientation="h")
    )
    st.plotly_chart(fig_consumo, use_container_width=True)

    st.warning("⚠️ **Riesgo Regulatorio Ambiental:** ALTO. Se recomienda una auditoría de huella de carbono.")


# --- MÓDULO 4: HSEQ ---
def display_modulo_hseq(df_data, horizon):
    """Módulo 4: Riesgos y Cumplimiento (HSEQ + Legal + Laboral)."""
    st.subheader("Costo de la No-Conformidad y Accidentalidad")

    costo_no_conformidad = np.random.randint(20_000_000, 40_000_000)
    incidencia_legal = np.random.uniform(0.5, 2.5)

    col1, col2 = st.columns(2)
    with col1:
        display_kpi_card("Costo Anual No-Conformidad", costo_no_conformidad, 0, format_string="COP {:,}")
    with col2:
        display_kpi_card("Índice de Incidencia Legal", incidencia_legal, None, format_string="{:.2f}")

    st.error("🚨 **Riesgo de Accidentalidad:** MODERADO. Se necesita un plan de acción para reducir el riesgo laboral.")

# --- MÓDULO 5: RRHH ---
def display_modulo_rrhh(df_data, horizon):
    """Módulo 5: Sostenibilidad Social (RRHH)."""

    df, _ = get_placeholder_data(horizon)
    tasa_retencion = df['Tasa_Retencion_RRHH'].mean()
    costo_cap_humano = np.random.randint(100_000_000, 200_000_000)

    col1, col2 = st.columns(2)
    with col1:
        display_kpi_card("Tasa de Retención Actual", tasa_retencion, -1.5, format_string="{:.1f}%")
    with col2:
        display_kpi_card("Costo Anual del Capital Humano", costo_cap_humano, None, format_string="COP {:,}")

    st.markdown("---")
    st.subheader("Gráfico: Tasa de Retención Histórica")

    fig_retencion = px.bar(df, x='FECHA', y='Tasa_Retencion_RRHH',
                           title='Evolución de la Tasa de Retención',
                           labels={'Tasa_Retencion_RRHH': 'Tasa (%)', 'FECHA': 'Fecha'})
    st.plotly_chart(fig_retencion, use_container_width=True)
    st.info(f"Proyección a **{horizon} meses**: El riesgo de retención aumenta levemente debido a la falta de programas de desarrollo.")

# --- MÓDULO 6: COMERCIAL ---
def display_modulo_comercial(df_data, horizon):
    """Módulo 6: Comercial (Ingresos y Precios Óptimos)."""

    df, _ = get_placeholder_data(horizon)
    clientes_activos = df['Clientes_Activos'].mean().round(0)
    aov = df['Valor_Promedio_Venta'].mean()
    costo_rotacion_base = np.random.randint(5_000_000, 10_000_000)

    col1, col2, col3 = st.columns(3)
    with col1:
        display_kpi_card("Clientes Activos Promedio", clientes_activos, 5)
    with col2:
        display_kpi_card("Valor Promedio de Venta (AOV)", aov, 1.5, format_string="COP {:,}")
    with col3:
        display_kpi_card("Costo Rotación Base", costo_rotacion_base, None, format_string="COP {:,}")

    st.markdown("---")
    st.subheader("Gráfico: Evolución Histórica de Ventas")

    fig_ventas = px.bar(df, x='FECHA', y='Ventas_Gravadas',
                        title='Ventas Gravadas Mensuales',
                        labels={'Ventas_Gravadas': 'Ventas (COP)', 'FECHA': 'Fecha'},
                        color_discrete_sequence=px.colors.qualitative.T10)
    st.plotly_chart(fig_ventas, use_container_width=True)


# --- MÓDULO 7: PRODUCTIVIDAD ---
def display_modulo_productividad(df_data, horizon):
    """Módulo 7: Productividad y Procesos (Eficiencia Operativa y Costos Ocultos)."""

    df, _ = get_placeholder_data(horizon)
    tasa_defectos_base = df['Tasa_Defectos'].mean()
    costo_oculto_base = df['Costo_Oculto'].sum()

    st.subheader("Simulación de Reducción de Costos Ocultos")

    with st.expander("⚙️ Simulación de Mejora en Procesos"):
        reduccion_defectos_pct = st.slider("Reducción Meta en Tasa de Defectos (%)", min_value=0.0, max_value=50.0, value=10.0, step=1.0)

        nueva_tasa_defectos = tasa_defectos_base * (1 - reduccion_defectos_pct / 100)
        reduccion_costo_proyectada = costo_oculto_base * (reduccion_defectos_pct / 100)

    col1, col2 = st.columns(2)
    with col1:
        display_kpi_card("Tasa de Defectos (Base)", tasa_defectos_base, None, format_string="{:.2f}%")
        st.metric("Tasa Proyectada (Mejora)", f"{nueva_tasa_defectos:.2f}%", f"{(tasa_defectos_base - nueva_tasa_defectos):.2f}% menos")
    with col2:
        display_kpi_card("Costo Oculto (Base)", costo_oculto_base, None, format_string="COP {:,}")
        st.metric("Ahorro Proyectado", f"COP {reduccion_costo_proyectada:,.0f}", "Ahorro Estimado")

    st.markdown("---")
    st.subheader("Gráfico: Tasa de Defectos Histórica")
    fig_defectos = px.line(df, x='FECHA', y='Tasa_Defectos',
                           title='Tasa de Defectos por Mes',
                           labels={'Tasa_Defectos': 'Tasa (%)', 'FECHA': 'Fecha'},
                           markers=True)
    st.plotly_chart(fig_defectos, use_container_width=True)


# --- FLUJO PRINCIPAL DE LA APLICACIÓN ---
if __name__ == "__main__":
    if check_password():
        # --- Sidebar ---
        connect_to_sql_db()
        load_data_from_upload()

        # --- Cabecera Post-Login (Según DOCX) ---
        st.title("ACUAMAR S.A.")
        st.caption("Empresa manufacturera y distribuidora de productos químicos de limpieza e higiene industrial")

        # Funcionalidad 5: BARRA DE PREDICCIÓN (Slider global)
        horizonte_proyeccion = st.slider(
            "Horizonte (Meses): Periodo para todas las proyecciones y simulaciones.",
            min_value=1,
            max_value=36,
            value=HORIZONTE_PROYECCION_DEFAULT,
            step=1,
            key='global_horizonte'
        )
        st.markdown("---")

        # --- Navegación por Módulos (Tabs) ---

        tabs_list = st.tabs(list(MODULOS.values()))

        df_actual = st.session_state.get('df_data')

        # Mapeo de funciones a pestañas
        module_functions = [
            display_modulo_gobernanza,
            display_modulo_financiero,
            display_modulo_ambiental,
            display_modulo_hseq,
            display_modulo_rrhh,
            display_modulo_comercial,
            display_modulo_productividad
        ]

        # Renderizado de pestañas
        for i, tab in enumerate(tabs_list):
            with tab:
                module_functions[i](df_actual, horizonte_proyeccion)